# Generated by Django 5.0.1 on 2024-03-28 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_url', models.URLField()),
                ('product_data', models.JSONField()),
                ('version', models.CharField(max_length=255)),
                ('backup_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
