# Generated by Django 5.0.1 on 2024-03-29 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='backup_date',
            field=models.DateField(default=datetime.date(2024, 3, 29)),
        ),
    ]
