# Generated by Django 5.0.1 on 2024-03-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_alter_product_backup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
    ]
