# Generated by Django 5.0.1 on 2024-03-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_remove_product_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
