# Generated by Django 5.0.1 on 2024-03-29 07:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_product_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3')], max_length=100)),
                ('data', models.JSONField()),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('backup_date', models.DateField(default=datetime.date(2024, 3, 29))),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.UUIDField(primary_key=True, serialize=False)),
                ('Organization_name', models.CharField(max_length=100)),
                ('store_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='object',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.store'),
        ),
    ]
